const Images = {
  logo: require("../images/instincthub.png"),
  img1: require("../images/img1.jpg"),
  img2: require("../images/img2.jpg"),
  img3: require("../images/img3.jpg"),
  img4: require("../images/img4.jpg"),
  img5: require("../images/img5.jpg"),
  img6: require("../images/img6.jpg"),
  img7: require("../images/img7.jpg"),
  blog1: require("../images/blog1.jpg"),
  blog2: require("../images/blog2.jpg"),
  blog3: require("../images/blog3.jpg"),
  blog4: require("../images/blog4.jpg"),

  casual: require("../images/Casual-life.png"),
  casual2: require("../images/casual2.png"),
  carosel1: require("../images/carosel1.png"),
  testimonial_b: require("../images/testimonial-b.png"),
  feature1: require("../images/feature1.png"),
  talentQl: require("../images/talentQl.png"),
  enterprise: require("../images/enterprise.png"),
  // kidscancode: require("../images/kidscancode.png"),
  kidscancode: require("../images/kidscancode.gif"),
  about: require("../images/about.png"),
  eyowo: require("../images/eyowo.png"),
  andela: require("../images/andela.png"),
  about_process: require("../images/about_process.png"),
  piggyvest: require("../images/piggyvest.png"),
  andela: require("../images/andela.png"),
  yellowCard: require("../images/yellow_card.png"),
  individual: require("../images/individual.png"),
  kidsgif: require("../images/kidsgif.gif"),
  enterprise_landing: require("../images/enterprise_landing.png"),
  workspace: require("../images/workspace.png"),
  workstation: require("../images/workstation.png"),
  laptop: require("../images/laptop.png"),
  videogif: require("../images/videogif.gif"),
  on_phone: require("../images/on_phone.jpg"),
  DayOne: require("../images/Dayone.png"),
  empathy: require("../images/empathy.png"),
  Humility: require("../images/Humility.png"),
  Ownership: require("../images/Ownership.png"),
};
export default Images;
