const Images = {
  logo: require("../images/instincthub.png"),
  casual: require("../images/Casual-life.png"),
  casual2: require("../images/casual2.png"),
  carosel1: require("../images/carosel1.png"),
  testimonial_b: require("../images/testimonial-b.png"),
  feature1: require("../images/feature1.png"),
  talentQl: require("../images/talentQl.png"),
  // kidscancode: require("../images/kidscancode.png"),
  kidscancode: require("../images/kidscancode.gif"),
  eyowo: require("../images/eyowo.png"),
  andela: require("../images/andela.png"),
  piggyvest: require("../images/piggyvest.png"),
  andela: require("../images/andela.png"),
  yellowCard: require("../images/yellow_card.png"),
  individual: require("../images/individual.png"),
  kidsgif: require("../images/kidsgif.gif"),
  enterprise_landing: require("../images/enterprise_landing.png"),
  workspace: require("../images/workspace.png"),
  videogif: require("../images/videogif.gif"),
  on_phone: require("../images/on_phone.jpg"),
};
export default Images;
