export const Data = [
  {
    id: 1,
    first_name: "Verile",
    last_name: "Arnhold",
    email: "varnhold0@vkontakte.ru",
    text: "eget nunc donec quis orci eget orci vehicula condimentum curabitur in libero ut massa volutpat convallis morbi odio",
    img: "http://dummyimage.com/196x100.png/dddddd/000000",
  },
  {
    id: 2,
    first_name: "Olva",
    last_name: "Bertolaccini",
    email: "obertolaccini1@phpbb.com",
    text: "ante vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae duis faucibus accumsan",
    img: "http://dummyimage.com/146x100.png/cc0000/ffffff",
  },
  {
    id: 3,
    first_name: "Jada",
    last_name: "Ollive",
    email: "jollive2@blog.com",
    text: "pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin mi sit amet lobortis sapien sapien non",
    img: "http://dummyimage.com/135x100.png/dddddd/000000",
  },
  {
    id: 4,
    first_name: "Layney",
    last_name: "Chamberlaine",
    email: "lchamberlaine3@cafepress.com",
    text: "quam pede lobortis ligula sit amet eleifend pede libero quis orci nullam",
    img: "http://dummyimage.com/239x100.png/5fa2dd/ffffff",
  },
  {
    id: 5,
    first_name: "Conan",
    last_name: "McCalister",
    email: "cmccalister4@tamu.edu",
    text: "quam sapien varius ut blandit non interdum in ante vestibulum ante ipsum primis in faucibus orci luctus et",
    img: "http://dummyimage.com/113x100.png/5fa2dd/ffffff",
  },
  {
    id: 6,
    first_name: "Gustave",
    last_name: "Monnoyer",
    email: "gmonnoyer5@ask.com",
    text: "suspendisse potenti nullam porttitor lacus at turpis donec posuere metus vitae ipsum aliquam non mauris morbi non lectus",
    img: "http://dummyimage.com/152x100.png/ff4444/ffffff",
  },
  {
    id: 7,
    first_name: "Leonie",
    last_name: "Selby",
    email: "lselby6@pinterest.com",
    text: "et commodo vulputate justo in blandit ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing",
    img: "http://dummyimage.com/180x100.png/dddddd/000000",
  },
  {
    id: 8,
    first_name: "Joaquin",
    last_name: "Henrys",
    email: "jhenrys7@biglobe.ne.jp",
    text: "sollicitudin vitae consectetuer eget rutrum at lorem integer tincidunt ante vel ipsum praesent blandit lacinia",
    img: "http://dummyimage.com/110x100.png/5fa2dd/ffffff",
  },
  {
    id: 9,
    first_name: "Sharona",
    last_name: "Woodley",
    email: "swoodley8@shareasale.com",
    text: "erat curabitur gravida nisi at nibh in hac habitasse platea dictumst aliquam augue",
    img: "http://dummyimage.com/149x100.png/ff4444/ffffff",
  },
  {
    id: 10,
    first_name: "Elora",
    last_name: "Pegler",
    email: "epegler9@mashable.com",
    text: "curae donec pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin mi sit amet lobortis sapien sapien non",
    img: "http://dummyimage.com/243x100.png/dddddd/000000",
  },
  {
    id: 11,
    first_name: "Belita",
    last_name: "Davidsen",
    email: "bdavidsena@jimdo.com",
    text: "eget tempus vel pede morbi porttitor lorem id ligula suspendisse ornare consequat lectus in est risus",
    img: "http://dummyimage.com/154x100.png/5fa2dd/ffffff",
  },
  {
    id: 12,
    first_name: "Jacquie",
    last_name: "Swate",
    email: "jswateb@forbes.com",
    text: "nunc purus phasellus in felis donec semper sapien a libero nam dui proin leo odio",
    img: "http://dummyimage.com/246x100.png/ff4444/ffffff",
  },
  {
    id: 13,
    first_name: "Carlina",
    last_name: "Donat",
    email: "cdonatc@cnbc.com",
    text: "consequat dui nec nisi volutpat eleifend donec ut dolor morbi vel lectus in quam fringilla rhoncus mauris",
    img: "http://dummyimage.com/196x100.png/dddddd/000000",
  },
  {
    id: 14,
    first_name: "Ives",
    last_name: "MacTurlough",
    email: "imacturloughd@msn.com",
    text: "enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin interdum mauris non ligula pellentesque ultrices phasellus id",
    img: "http://dummyimage.com/184x100.png/ff4444/ffffff",
  },
  {
    id: 15,
    first_name: "Stephine",
    last_name: "Kidston",
    email: "skidstone@theguardian.com",
    text: "felis ut at dolor quis odio consequat varius integer ac leo pellentesque ultrices mattis odio",
    img: "http://dummyimage.com/191x100.png/dddddd/000000",
  },
  {
    id: 16,
    first_name: "Windy",
    last_name: "Bernhardt",
    email: "wbernhardtf@toplist.cz",
    text: "risus auctor sed tristique in tempus sit amet sem fusce consequat nulla nisl nunc",
    img: "http://dummyimage.com/201x100.png/cc0000/ffffff",
  },
  {
    id: 17,
    first_name: "Abbott",
    last_name: "Renfrew",
    email: "arenfrewg@prnewswire.com",
    text: "lectus in est risus auctor sed tristique in tempus sit amet sem fusce consequat nulla nisl nunc nisl",
    img: "http://dummyimage.com/218x100.png/dddddd/000000",
  },
  {
    id: 18,
    first_name: "Elisabet",
    last_name: "Habbema",
    email: "ehabbemah@friendfeed.com",
    text: "lacinia erat vestibulum sed magna at nunc commodo placerat praesent blandit nam nulla integer pede justo",
    img: "http://dummyimage.com/238x100.png/cc0000/ffffff",
  },
  {
    id: 19,
    first_name: "Lanny",
    last_name: "Snawdon",
    email: "lsnawdoni@lulu.com",
    text: "vitae nisl aenean lectus pellentesque eget nunc donec quis orci",
    img: "http://dummyimage.com/155x100.png/cc0000/ffffff",
  },
  {
    id: 20,
    first_name: "Arther",
    last_name: "Shropsheir",
    email: "ashropsheirj@nsw.gov.au",
    text: "rutrum ac lobortis vel dapibus at diam nam tristique tortor eu",
    img: "http://dummyimage.com/156x100.png/dddddd/000000",
  },
];
