const SVGs = {
  instincthub_logo: require("../svg/logo.svg").default,
  email: require("../svg/location.svg").default,
  location: require("../svg/location.svg").default,
  phone: require("../svg/phone.svg").default,
  facebook: require("../svg/facebook.svg").default,
  youtube: require("../svg/youtube.svg").default,
  linkedin: require("../svg/linkedin.svg").default,
  twitter: require("../svg/twitter.svg").default,
  instagram: require("../svg/instagram.svg").default,
  css: require("../svg/css.svg").default,
  django: require("../svg/django.svg").default,
  html: require("../svg/html.svg").default,
  js: require("../svg/js.svg").default,
  php: require("../svg/php.svg").default,
  python: require("../svg/python.svg").default,
  react: require("../svg/react.svg").default,
  accessable: require("../svg/accessable.svg").default,
  affordable: require("../svg/affordable.svg").default,
  community: require("../svg/community.svg").default,
  support: require("../svg/support.svg").default,
  group: require("../svg/group.svg").default,
  clock: require("../svg/clock.svg").default,
  brief: require("../svg/brief.svg").default,
  creation: require("../svg/creation.svg").default,
  handoff: require("../svg/handoff.svg").default,
  reviews: require("../svg/reviews.svg").default,
  bulb: require("../svg/bulb.svg").default,
  call: require("../svg/call.svg").default,
  sterling: require("../svg/sterling.svg").default,
  critical_thinking: require("../svg/critical_thinking.svg").default,
  problem_solving: require("../svg/problem_solving.svg").default,
};
export default SVGs;
